# Generated by Django 5.2.3 on 2025-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Game Active'), ('finished', 'Game Finished')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('max_players', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
