# Generated by Django 5.2.3 on 2025-06-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Game Categories',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rounds', models.IntegerField(default=10)),
                ('round_time_seconds', models.IntegerField(default=30)),
                ('unique_answer_points', models.IntegerField(default=10)),
                ('valid_answer_points', models.IntegerField(default=5)),
                ('invalid_answer_points', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, to='game_sessions.gamecategory')),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='game_sessions.gamesession')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_sessions.gametype')),
            ],
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='game_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='game_sessions.gametype'),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('prompt_letter', models.CharField(max_length=1)),
                ('prompt_text', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_sessions.gamecategory')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('game_session', 'round_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gamecategory',
            unique_together={('name', 'game_type')},
        ),
    ]
