# Generated by Django 5.2.3 on 2025-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_gamecategory_gametype_gameconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_round_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_round_active',
            field=models.BooleanField(default=False),
        ),
    ]
