# Generated by Django 5.2.3 on 2025-06-21 17:53

from django.db import migrations


def set_default_round_values(apps, schema_editor):
    """Set default values for existing GameSession records"""
    GameSession = apps.get_model('game_sessions', 'GameSession')
    GameSession.objects.filter(current_round_number__isnull=True).update(current_round_number=0)
    GameSession.objects.filter(is_round_active__isnull=True).update(is_round_active=False)


def reverse_default_round_values(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_gamesession_current_round_number_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_round_values, reverse_default_round_values),
    ]
