# Generated by Django 5.2.3 on 2025-06-21 17:53

from django.db import migrations


def set_default_round_values(apps, _schema_editor):
    """
    Sets default values for null fields in existing GameSession records.
    
    Updates all GameSession entries with a null `current_round_number` to 0 and those with a null `is_round_active` to False.
    """
    GameSession = apps.get_model('game_sessions', 'GameSession')
    GameSession.objects.filter(current_round_number__isnull=True).update(current_round_number=0)
    GameSession.objects.filter(is_round_active__isnull=True).update(is_round_active=False)


def reverse_default_round_values(apps, _schema_editor):
    """
    No-op reverse migration function; does nothing when the migration is rolled back.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_gamesession_current_round_number_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_round_values, reverse_default_round_values),
    ]
