# Generated by Django 5.2.3 on 2025-06-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0005_alter_gameround_unique_together_and_more'),
        ('players', '0004_alter_playeranswer_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameRound',
        ),
    ]
