# Generated by Django 5.2.3 on 2025-06-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0006_delete_gameround'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfiguration',
            name='round_type_sequence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
