# Generated by Django 5.2.4 on 2025-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0008_multiplechoicequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
