# Generated by Django 5.2.4 on 2025-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0009_multiplechoicequestion_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
