# Generated by Django 5.2.4 on 2025-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0010_multiplechoicequestion_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='is_specialist',
            field=models.BooleanField(default=False, help_text='True if this question is for a specialist subject (Mastermind rounds)'),
        ),
    ]
