# Generated by Django 5.2.4 on 2025-07-07 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0011_multiplechoicequestion_is_specialist'),
        ('players', '0009_player_specialist_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MastermindRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('state', models.CharField(choices=[('waiting_for_player_selection', 'Waiting for Player Selection'), ('asking_ready', 'Asking Player Ready'), ('playing', 'Playing Rapid Fire'), ('player_complete', 'Player Complete'), ('all_complete', 'All Players Complete')], default='waiting_for_player_selection', max_length=50)),
                ('current_question_index', models.IntegerField(default=0)),
                ('questions_per_player', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_players', models.ManyToManyField(blank=True, related_name='completed_mastermind_rounds', to='players.player')),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_mastermind_rounds', to='players.player')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastermind_rounds', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['game_session', 'round_number'],
                'unique_together': {('game_session', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='MastermindAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('selected_choice', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('mastermind_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.mastermindround')),
            ],
            options={
                'ordering': ['mastermind_round', 'player', 'question_index'],
                'unique_together': {('mastermind_round', 'player', 'question_index')},
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mastermind_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastermind.mastermindround')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'unique_together': {('mastermind_round', 'player')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mastermind.subject')),
            ],
            options={
                'ordering': ['usage_count', 'last_used'],
                'indexes': [models.Index(fields=['subject', 'usage_count', 'last_used'], name='mastermind__subject_41ed37_idx'), models.Index(fields=['subject', 'difficulty'], name='mastermind__subject_a81e7b_idx')],
            },
        ),
    ]
