# Generated by Django 5.2.4 on 2025-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermindround',
            name='current_phase',
            field=models.CharField(choices=[('specialist', 'Specialist Round'), ('general_knowledge', 'General Knowledge Round')], default='specialist', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastermindround',
            name='questions_per_player',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='mastermindround',
            name='state',
            field=models.CharField(choices=[('waiting_for_player_selection', 'Waiting for Player Selection'), ('asking_ready', 'Asking Player Ready'), ('playing', 'Playing Rapid Fire'), ('player_complete', 'Player Complete'), ('specialist_complete', 'Specialist Round Complete'), ('general_knowledge', 'General Knowledge Round'), ('all_complete', 'All Players Complete')], default='waiting_for_player_selection', max_length=50),
        ),
    ]
