# Generated by Django 5.2.4 on 2025-08-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastermind', '0002_mastermindround_current_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermindanswer',
            name='question_type',
            field=models.CharField(choices=[('specialist', 'Specialist'), ('general_knowledge', 'General Knowledge')], default='specialist', max_length=20),
        ),
        migrations.CreateModel(
            name='GeneralKnowledgeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('category', models.CharField(default='General Knowledge', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['usage_count', 'last_used'],
                'indexes': [models.Index(fields=['usage_count', 'last_used'], name='mastermind__usage_c_db8a27_idx'), models.Index(fields=['difficulty'], name='mastermind__difficu_fd1107_idx')],
            },
        ),
    ]
