# Generated by Django 5.2.3 on 2025-06-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_gamesession_current_round_number_and_more'),
        ('players', '0002_playeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranswer',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game_sessions.gameround'),
        ),
    ]
