# Generated by Django 5.2.3 on 2025-06-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0005_alter_gameround_unique_together_and_more'),
        ('players', '0003_playeranswer_round_number_alter_playeranswer_round'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playeranswer',
            unique_together={('player', 'round_number')},
        ),
        migrations.AddField(
            model_name='player',
            name='current_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('points_change', models.IntegerField()),
                ('reason', models.CharField(default='points_awarded', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='game_sessions.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='players.player')),
                ('related_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.playeranswer')),
            ],
            options={
                'verbose_name_plural': 'Score histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='round',
        ),
    ]
