# Generated by Django 5.2.3 on 2025-06-21 21:31

from django.db import migrations
from django.db.models import Sum


def populate_current_scores(apps, schema_editor):
    """Populate current_score field from existing PlayerAnswer data"""
    Player = apps.get_model('players', 'Player')
    PlayerAnswer = apps.get_model('players', 'PlayerAnswer')

    for player in Player.objects.all():
        total_score = PlayerAnswer.objects.filter(
            player=player
        ).aggregate(total=Sum('points_awarded'))['total'] or 0

        player.current_score = total_score
        player.save()


def reverse_populate_current_scores(apps, schema_editor):
    """Reverse migration - reset all current_score to 0"""
    Player = apps.get_model('players', 'Player')
    Player.objects.update(current_score=0)


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_playeranswer_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_current_scores, reverse_populate_current_scores),
    ]
