# Generated by Django 5.2.3 on 2025-06-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correct_answer_streak',
            field=models.IntegerField(default=0),
        ),
    ]
