# Generated by Django 5.2.4 on 2025-07-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_player_correct_answer_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeranswer',
            name='round_number',
            field=models.IntegerField(),
        ),
    ]
