# Generated by Django 5.2.4 on 2025-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_remove_round_number_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='specialist_subject',
            field=models.CharField(blank=True, help_text="Player's specialist subject for Mastermind rounds", max_length=100, null=True),
        ),
    ]
